- CHANGELOG.md
- README.md
- lib/omniauth-saml/version.rb
- lib/omniauth/strategies/saml.rb
- omniauth-saml.gemspec
- spec/omniauth/strategies/saml_spec.rb
If the option `idp_cert_fingerprint_validator` is present, it's a one parameter lambda that verifies if the idp fingerprint coming from the request is valid. The lambda is called and, if the response is successful, the fingerprint is valid and is used thereafter.
In some situations there's the need to support **multiple** fingerprints in a dynamic way. Fingerprints might be available on a database or elsewhere and the best way to abstract their validation is to provide a method that will verify if a given fingerprint exists.
This feature will, in fact, support multiple dynamic fingerprint usage without prior configuration.
This feature shouldn't break any existing functionality. It will only be used and activated if the `idp_cert_fingerprint_validator` option is present.
> Validate an idp fingerprint using a configurable lambda

- README.md
- lib/omniauth/strategies/saml.rb
- spec/omniauth/strategies/saml_spec.rb
Adds the omniauth's required user attributes to the `metadata.xml` as a `AttributeConsumingService` element per [section 2.4.4.1 of the metadata spec](http://docs.oasis-open.org/security/saml/v2.0/saml-metadata-2.0-os.pdf). Configurable via `:request_attributes` and `:attribute_service_name`. 
The current options don't support assigning to the `OneLogin::RubySaml::Settings#attribute_consuming_service`.
> Configurable attribute_consuming_service

- Gemfile.lock
- lib/omniauth-saml/version.rb
- omniauth-saml.gemspec
Ruby SAML 1.1 was released a couple of months ago and includes some important [changes](https://github.com/onelogin/ruby-saml/blob/master/changelog.md), most importantly the support for SAMLResponse without ds:x509certificate.
This is needed for some environments where GitLab EE is running.
Also bumped the version to 1.4.1 to release a new gem.
> Update `ruby-saml` to 1.1

- lib/omniauth/strategies/saml.rb
I proposed this change in #55. This will call `valid?` earlier, so that the real error checking in `ruby-saml` happens before the blank check on `@name_id`, resulting in more meaningful errors in case something is wrong with the SAML response.
> Call validation earlier to get real error instead of 'response missing name_id'

- Gemfile.lock
- omniauth-saml.gemspec
- spec/omniauth/strategies/saml_spec.rb
This PR updates `Omniauth::Strategies::SAML` to avoid mutating the `options` hash during `request_phase` and `callback_phase`. This mutation was the underlying cause of the failure reported in #54.
This PR is an alternative to the fix proposed in #56, since `deep_dup` is Rails-specific.
Let me know if you want me to drop the `Gemfile.lock` changes.
Also, I targeted this at the `master` branch instead of the `develop` branch because the latter branch is now behind.
Fixes #54
> Add specs for ACS fallback URL behavior

- README.md
- lib/omniauth/strategies/saml.rb
- spec/omniauth/strategies/saml_spec.rb
- spec/support/custom_attributes.xml
This PR replaces #51. Here is @OsQu's description from that PR:
> Attribute statements might not always have a Name="firstName" attribute, and modifying the idp to support can be an exhausting task (e.g. ADFS).
> 
> Now one can give attribute_statements option, which contains a mapping from statements to an info hash. For example the default mapping is following:
> ```
>   option :attribute_statements, {
name: ["name"],
email: ["email", "mail"],
first_name: ["first_name", "firstname", "firstName"],
last_name: ["last_name", "lastname", "lastName"]
}
> ```
> This we can support whatever weird configurations the other end might have, without hard-coding them directly to the source.
Closes #45, #49, #51
> Support custom attributes

- LICENSE.md
- README.md
- omniauth-saml.gemspec
A widely adopted best practice is having a LICENSE.md file, so I've moved the license out from README.md to a dedicated file.
> docs: move license from README.md to LICENSE.md

- lib/omniauth/strategies/saml.rb
> Initialize OneLogin::RubySaml::Response instance with settings

- .gitignore
- spec/omniauth/strategies/saml_spec.rb
Fixed the `saml-spec.rb` file and added the `.idea/` folder to the `.gitignore` file for people that use RubyMine as their preferred IDE, like me.
> Fixed specs to make them compatible with `ruby-saml` 1.1.2

- .travis.yml
- gemfiles/ruby-1.8.7.gemfile
> chore: remove ruby 1.8.7 support

- .travis.yml
- lib/omniauth/strategies/saml.rb
- spec/omniauth/strategies/saml_spec.rb
This is a trivial change that will make it easier for [omniauth-multi-provider-saml](https://github.com/salsify/omniauth-multi-provider-saml) to override the method, so it can properly route `/auth/saml/:provider/metadata` to display per-provider metadata.
Some background: for multi-provider SAML, each SAML provider has a unique identifier that scopes all the omniauth paths for it -- e.g. `/auth/saml/myprovider/callback`, `/auth/saml/otherguys/callback`. But the metadata route is broken, as this gem hard-codes the expected path to just `/auth/saml/metadata`. So short of copying the entire `other_phase` method, there's no good workaround (multi-provider-saml passes in a proc value for `request_path`, which `Omniauth::Strategy` [just …
> Extract metadata route logic to a separate method

- .travis.yml
- lib/omniauth/strategies/saml.rb
- spec/omniauth/strategies/saml_spec.rb
This PR updates `OmniAuth::Strategies::SAML` to register any subclasses as strategies with OmniAuth. This parallels what's done in the `omniauth-oauth2` gem (cf. [here](https://github.com/intridea/omniauth-oauth2/blob/26152673224aca5c3e918bcc83075dbb0659717f/lib/omniauth/strategies/oauth2.rb#L17-L19)).
> Register subclasses with OmniAuth.strategies

- CHANGELOG.md
- omniauth-saml.gemspec
This PR updates `ruby-saml` to 1.3.0 to address [CVE-2016-5697](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-5697) signature wrapping attacks as [recommended](https://github.com/omniauth/omniauth-saml/issues/96#issuecomment-228411928) by `ruby-saml` maintainer @pitbulk.
> Update ruby-saml to 1.3.0

- README.md
- lib/omniauth/strategies/saml.rb
- spec/omniauth/strategies/saml_spec.rb
feat: added the Ruby-saml response object to the extra attribute, so we can use it in the controller via "env['omniauth.auth'].extra.response_object"
> feat: added the response object to the extra['response_object']

- lib/omniauth/strategies/saml.rb
- spec/omniauth/strategies/saml_spec.rb
Without issuer information, which gets translated to an `entityID` in the metadata XML, some IdPs are unable to auto-configure themselves using the metadata endpoint, which is what it was meant for.
This pull requests adds this missing information.
Example XML
```xml
<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="_8104ed3c-6f3f-43a0-9709-fc5d285bb1c8" entityID="https://localhost:3443/">
<md:SPSSODescriptor AuthnRequestsSigned="false" WantAssertionsSigned="false" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
<md:NameIDFormat>
urn:oasis:names:tc:SAML:2.0:nameid-format:transient
</md:NameIDFormat>
<md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" …
```
> Add issuer information to the metadata endpoint

- .gitignore
- CHANGELOG.md
- CONTRIBUTING.md
- omniauth-saml.gemspec
This is a spike for @bufferoverflow to see how we can integrate a [conventional changelog generator](https://github.com/conventional-changelog/conventional-changelog) into Ruby projects. Unfortunately there aren't many options, and I already ran into several issues with the [`conventional-changelog`](https://github.com/dcrec1/conventional-changelog-ruby) gem I'm using here:
- it's very basic, e.g. it only detects `feat` and `fix`
- the behaviour and CLI arguments are not very intuitive,  it's very easy to end up with commits listed under the wrong version header, and it's not possible to generate entries for previous releases either
- there's barely any error handling, wrong CLI arguments can result in an empty `CHANGELOG.md` file
I looked around a bit more for alternatives but couldn't …
> chore: Add conventional changelog generator

- Appraisals
- README.md
- gemfiles/rack_1.gemfile
- lib/omniauth/strategies/saml.rb
- spec/omniauth/strategies/saml_spec.rb
- spec/support/example_logout_request.xml
- spec/support/example_logout_response.xml
Replaces #99, as the author there has not responded and we would really like to have this feature for version 1.7.0.
Fixes #81
@md5 can you help me with a review here? I tried solving the conflicts to the best of my abilities, and the tests are green, but I really need more eyes here to make sure the code is sound.
cc @bufferoverflow
> feat: Support for Single Logout

- omniauth-saml.gemspec
We might want to add this for 1.7.0
cc @bufferoverflow @md5
> Bump `ruby-saml` dependency to 1.4.0

- README.md
- lib/omniauth/strategies/saml.rb
- spec/omniauth/strategies/saml_spec.rb
Some SAML 2.0 IdPs use the transient name identifier format. In that case the name identifier changes for each login, which makes the name identifier unsuitable as a user identifier.
This patch introduces the `uid_attribute` option, that allows us to use a SAML 2.0 attribute as the user identifier instead of the name identifier.
Fixes issue #120.
*Note*: It was suggested in [this issue comment](https://github.com/omniauth/omniauth-saml/issues/120#issuecomment-260744835) that this patch should also make the name identifier optional. I decided to not do that, since that also has implications for logout. I therefore think that makes more sense as a separate patch.
> Add `uid_attribute` option to control the attribute used for the user id

- README.md
- lib/omniauth/strategies/saml.rb
There are certain authentication libraries (e.g. Clearance) that do not use the browser session to perform logouts.
For this reason, I propose adding a provider configuration option `idp_slo_session_destroy`, which takes a proc given the current rack environment and session so that additional logout measures can be taken. The previous `session.clear` functionality has been made the default of this option.
> feat: Support for configurable IdP SLO session destruction

- README.md
Closes omniauth/omniauth-saml#127.
> docs: clarify SP metadata URL when using Devise

- lib/omniauth/strategies/saml.rb
Some idp's use the sessionindex rather than the uid to find the correct
session to sign out. I've made this work by saving it in the session
alongside the uid, then putting it back into the logout request where
ruby-saml can handle it, and include it in the logout request.
> feat: include SessionIndex in logout requests

- lib/omniauth/strategies/saml.rb
- spec/omniauth/strategies/saml_spec.rb
While extending the specs to increase the coverage, I noticed that `OmniAuth::Strategies::SAML::ValidationError` exceptions are not handled in the `other_request` phase. This will result in returning `500 Server Error` responses, while some `4xx` error would be probably be more appropriate.
> Chore: Increase Coverage

- README.md
- omniauth-saml.gemspec
***Should not be merged before onelogin/ruby-saml#393 is in their master***
Fixes #83
> Chore: Add section about parsing IdP metadata to README

- lib/omniauth/strategies/saml.rb
- spec/omniauth/strategies/saml_spec.rb
Fix a bug where ruby-saml would fail SubjectConfirmation Recipient
validation when using the default assertion_consumer_service_url. The
url was not being set during the callback phase.
This closes #139
> fix: default assertion_consumer_service_url not set during callback

- omniauth-saml.gemspec
CVE-2017-18076 describes a bug in omniauth prior to version 1.3.2 (https://nvd.nist.gov/vuln/detail/CVE-2017-18076). This pull request upgrades the version of omniauth to 1.3.2 or later.
> Update omniauth gem to 1.3.2 or later 1.3.x

- lib/omniauth/strategies/saml.rb
- omniauth-saml.gemspec
In https://github.com/onelogin/ruby-saml/pull/454 was introduced a whitelisting for allowed Response options.
In my previous pr https://github.com/omniauth/omniauth-saml/pull/159 I added one more option.
According to me, this whitelist introduced in 4712e9990dbcb768286941d2f7f50e1b0e048d49 should not be a responsibility of `omniauth-saml` but it should be provided out of the box by `ruby-saml`.  It looked like @md5 agreed on this point (https://github.com/omniauth/omniauth-saml/pull/159#issuecomment-376233630)
Since `'ruby-saml' ~>1.8` integrated this change, I updated the dependency of this gem and retrieved response available options from it.
> Retrieves response available options from ruby-saml

- README.md
according to saml doc saml session index has to be preserved as well as saml uid
From http://docs.oasis-open.org/security/saml/v2.0/saml-profiles-2.0-os.pdf :
**4.4.3.2 Identity Provider Determines Session Participants**
_If the logout profile is initiated by an identity provider, or upon receiving a valid `<LogoutRequest>`
message, the identity provider processes the request as defined in [SAMLCore]. It **MUST** examine the
**identifier** and **`<SessionIndex>`** elements and determine the set of sessions to be terminated._
> Update readme for Single Logout

- lib/omniauth-saml/version.rb
- omniauth-saml.gemspec
- spec/omniauth/strategies/saml_spec.rb
- spec/spec_helper.rb
OmniAuth 2.0.0 only allows POST by default, which the tests here reflect now. 
As there is no _library_ code changed, I believe this should be fine as a patch version change. 
Edit: bumped it to a major after discussion externally
[OmniAuth 2.0.0 release notes](https://github.com/omniauth/omniauth/releases/tag/v2.0.0)
Closes #196
> Allow OmniAuth 2.0.0

- README.md
- lib/omniauth/strategies/saml.rb
- spec/omniauth/strategies/saml_spec.rb
I started using the `omniauth-saml` gem a few days ago. While implementing SSO and SLO functionality, I noticed a discrepancy between the settings of the current `ruby-saml` gem and this gem. This MR is intended to fix these:
- `settings.issuer` has been renamed to `settings.sp_entity_id` with [`ruby-saml` 1.11.0](https://github.com/onelogin/ruby-saml/blob/master/CHANGELOG.md#1110-jul-24-2019)
- `settings.idp_sso_target_url` has been renamed to `settings.idp_sso_service_url` with [`ruby-saml` 1.12.0](https://github.com/onelogin/ruby-saml/blob/master/UPGRADING.md#upgrading-from-111x-to-1120)
- `settings.idp_slo_target_url` has been renamed to `settings.idp_slo_service_url` with [`ruby-saml` 1.12.0](https://github.com/onelogin/ruby-saml/blob/master/UPGRADING.md#upgrading-from-111x-to-1120) …
> Rename usage of deprecated SAML options

- README.md
Though this code is already not copy-pasteable as valid Ruby (due to the trailing `...` at the end of the `idp_cert_multi` array), that's at least obviously invalid and fast enough to fix.
This missing comma, however, causes parser errors that are less obvious and should be added!
> Fix copy-pasteability of code example

- README.md
- omniauth-saml.gemspec
In #228, it was noted that the required_ruby_version setting for the gem was bumped between gem version 2.1.0 to 2.1.1.  This was addressed in e9d5238 and released as gem version 2.1.2.
Earlier today, gem version 1.10.4 was released in order to resolve https://github.com/advisories/GHSA-cvp8-5r8g-fhvq for older rubies (ref #229), however this also highlights an earlier case in which the required_ruby_version setting was bumped during a patch release.  In this case, between gem version 1.10.1 and 1.10.2, required_ruby_version was bumped from >=2.1 to >=2.4.
With this PR, I am requesting that the required_ruby_version change made in gem version 1.10.2 be reverted in order to expand the ability for users stuck on the 1.10.x tree to resolve GHSA-cvp8-5r8g-fhvq.
> fix: revert required_ruby_version to >=2.4 for 1.10.x

- lib/omniauth/strategies/saml.rb
- spec/omniauth/strategies/saml_spec.rb
This is a mini PR that merely includes actual error messages in logout request validation errors, giving people a chance to find out what's wrong when it's not working.
> feat: log errors on failed logout
